### ISSUE TITLE
[Bug + Suggestion] MALClient for PC

### ISSUE THREAD

**Issue by ZeroOmar** [Mordonus/MALClient#11]
## **First of all, thank you very much for MALClient for both PC and mobile.**
After using MALClient for a while I noticed that the grid view only shows **_The first 10 anime_**
like this:
![screenshot 51](https://cloud.githubusercontent.com/assets/18592104/14768566/0794df56-0a46-11e6-9ca4-ef65aae29b7c.png)
The workaround is by **opening one of the anime** to show its content and the rest of grid loads properly
like this:
![screenshot 54](https://cloud.githubusercontent.com/assets/18592104/14768589/5de2ce22-0a46-11e6-860c-21da5a0356e4.png)
## The other issue (not considered a bug)
The width of the details panel of the anime **(by default)** is a bit too wide at **1366x768** resolution 
so reducing it a bit will be much appreciated 

here is how it looks on grid view
![screenshot 54](https://cloud.githubusercontent.com/assets/18592104/14768628/b52ab8a6-0a47-11e6-8dc1-0ea2412b3a28.png)
![screenshot 52](https://cloud.githubusercontent.com/assets/18592104/14768630/bf8f4294-0a47-11e6-9090-f814ffe88b56.png)
and this is on list view
![screenshot 55](https://cloud.githubusercontent.com/assets/18592104/14768632/d579b152-0a47-11e6-83df-4cebbfe49d18.png)
![screenshot 56](https://cloud.githubusercontent.com/assets/18592104/14768633/d8c5ce22-0a47-11e6-9fe5-da924f50694f.png)
## As for the suggestion:
There is a plenty of space at the top panel **unlike mobile** so the bottom bar buttons can be moved to the top to save the space taken by the bottom bar
![screenshot](https://cloud.githubusercontent.com/assets/18592104/14768647/4e9bfc7a-0a48-11e6-8368-5bf8f52101c4.png)
 
Sorry for the long post

**Comment by Mordonus** [comment]
1. Hmm , that's odd as there's quite big margin on first batch of items before incremental loading. I'll investigate.
2. I was mainly adjusting this for 1920x1080 so that details tabs (general,details,reviews etc.) wouldn't get squeezed in scrolling container but I'll add some breakpoints for smaller resolutions.
4. List view got update in 3.4.48.0 and this should be resolved now. (update should be up within few hours)
3. Interface has still elements from mobile version as it was its origin, I'll continue to convert them to desktop friendly versions.

Thanks for feedback!

**Comment by ZeroOmar** [comment]
thank you 
the bug is fixed in update 3.4.48.0
![image](https://cloud.githubusercontent.com/assets/18592104/14797288/4df3b368-0b32-11e6-9eb0-34182e4e8cc1.png)

**Comment by Mordonus** [comment]
Glad to hear :)

**Comment by Mordonus** [comment]
2. This splitter thingy will now have smaller starting size, update is almost ready ^^. Anything above 1400px -> details pane has 535px (no pivot animation) , else pane has 420px.
