### ISSUE TITLE
New profile page

### ISSUE THREAD

**Issue by Mordonus** [Mordonus/MALClient#27]
So now profile page has landed on my workbench...

This is rough idea how I'm planning to lay everything out.
![image](https://cloud.githubusercontent.com/assets/6102530/15633239/fe1e0038-25a7-11e6-87d8-3fb1f8e49a7c.png)

Thoughts ideas, requests?
There will be navigation through various profiles and comments. Everything read-only as there's no api for this stuff.

**Comment by Mordonus** [comment]
2nd iteration:
![image](https://cloud.githubusercontent.com/assets/6102530/15634360/18c2e86c-25c2-11e6-8a53-7d6859044483.png)

![image](https://cloud.githubusercontent.com/assets/6102530/15634358/0d017a0c-25c2-11e6-8528-4164d1f28b08.png)

**Comment by ZeroOmar** [comment]
looks good.
also check if it scales on lower resolutions

**Comment by Mordonus** [comment]
![image](https://cloud.githubusercontent.com/assets/6102530/15634577/bfbd7812-25c7-11e6-815b-9509e13ea9c6.png)

Scaling is good enough imo, it's desktop version so I'm not going to go all the way down to phone resolutions :D

**Comment by ZeroOmar** [comment]
![cartoon 24](https://cloud.githubusercontent.com/assets/18592104/15634594/41b2a298-25c8-11e6-84cf-60776bd13677.jpg)

**Comment by Mordonus** [comment]
I did not manage to finish everything but I'm close... (thanks random storms!)

At least I have previews (aka. help me test that out)

Desktop x64:
https://onedrive.live.com/redir?resid=C8FF5587AF40716D!264854&authkey=!AMSlX_kGyKcbUps&ithint=file%2crar
Mobile ARM:
https://onedrive.live.com/redir?resid=C8FF5587AF40716D!264853&authkey=!APxlMNfDJ-aESpc&ithint=file%2crar

I did test them but not extremely thoroughly, so let's find some interesting things.

Rough changelog:
New profile page.
Fixed manga update crashes.
Adding item through search won't display 0 episodes total.

Mobile:
Resolved issues with item widths.
Swipe to increment has been disabled in calendar page.
Calendar page got a few minor tweaks.

**Comment by ZeroOmar** [comment]
I'm downloading it now
I'll test it and give you feedback once I'm done

**Comment by ZeroOmar** [comment]
## Desktop:
- Overall the app is stable 
- instead of the long vertical side bar, small horizontal dividers can do the trick

### Bugs
- switching profile pages is a bit slow when fetching user data (basically the whole app freezes until it loads) 
  This is what it looks when it's frozen the favorite anime group is the one from the previously visited profile
  ![screenshot 75](https://cloud.githubusercontent.com/assets/18592104/15658804/74fd6670-26c1-11e6-8efe-31738a8286df.png)
  and this is when it loads
  ![screenshot 79](https://cloud.githubusercontent.com/assets/18592104/15658867/449103ba-26c2-11e6-8f7f-8ae9a70dc22d.png)

- The watch ad button doesn't do anything (only shows this animation)

   ![screenshot 78](https://cloud.githubusercontent.com/assets/18592104/15658593/918db144-26be-11e6-90fd-2fdc2ffe28f2.png)
- The friends section shows only 10 friends

## Mobile:
- The new profile page fits perfectly :+1: 

### Bugs:
- after visiting several profiles and switching tabs alot, it crashed once but I couldn't get it to crash again (maybe it's a random crash)
- The watch ad button doesn't do anything
- The friends section shows only 10 friends



## notices:
- profile pages could use an anime/manga list button to visit others list (I know you can type the user name in the list but no one remembers user names to enter manually) 
- (this is not related to the current version) the grid items while loading collapses into itself as if the grid holds itself around the picture unlike the list view it maintains it's shape even without the picture
(maybe use a dummy picture to hold the grid while fetching the other pictures from MAL)
![screenshot 76](https://cloud.githubusercontent.com/assets/18592104/15658989/d9ad2aea-26c3-11e6-81c9-b32092e63d7c.png)

**Comment by Mordonus** [comment]
- I'll stick to this vertical bar for now, I want to experiment with this design later on.
- Fetching data will now display progress bars and data will be wiped out on profile navigation.

- Those ads will work only in certain countries as I see ad views in stats. The traffic is extremely small and it doesn't generate any kind of revenue so I'll probably remove this sometime soon.
- There are only 10 friends as I'm parsing main profile page which contains up to 10 friends, parsing dedicated friends page is something I'll do later.

- Because of how this profile nav is a bit inefficient with processing lots of unnecessary data as there's no other way (gimme new API already >.<), after multitude of navigations something may just go wrong, maybe just one odd crash...

- Added list navigation buttons
- Grid items will now do their best and stretch themselves as much as they can :)

**Comment by Mordonus** [comment]
Okay, I think I've got everything covered up + I found some more bugs.

I'll probably upload this to the store this evening:
Desktop x64:
https://onedrive.live.com/redir?resid=C8FF5587AF40716D!264904&authkey=!AIrbSv9CMgrZyw8&ithint=file%2crar
Mobile ARM:
https://onedrive.live.com/redir?resid=C8FF5587AF40716D!264905&authkey=!AGS1a4QP66FRyI8&ithint=file%2crar

**Comment by Mordonus** [comment]
Doned
