### ISSUE TITLE
Crashes in WP10 when updating status

### ISSUE THREAD

**Issue by michaelorloske** [Mordonus/MALClient#31]
Crashes whenever updating a title - adding a watched episode, changing status from plan to watch to watching, changing finish date, etc. problems seem to have started within the last week. Tried logging in/out, deleting caches, hard resetting phone - issue still persists. WP phone build 10586.338

**Comment by Mordonus** [comment]
Okay, I have this fixed. The problem is that MSFT doesn't certificate updates during weekends... Unless some miracle occurs update will go live on Monday :( Sorry.

Additionaly fixed: top anime images fixed (MAL has changed something in html)
Grid items will now display status/watched on unauthenticated items where applicable.

**Comment by Mordonus** [comment]
Aaand update is on the store... I'm sorry for these crashes :(
