### ISSUE TITLE
Just me wondering about a pinch of monetization...

### ISSUE THREAD

**Issue by Mordonus** [Mordonus/MALClient#43]
I was lately thinking about getting something out of this app as over the course of 6 months I got $19 (after taxes, fees and such) from donations and I devote considerate amounts of time into this project.

I'm not sure whether ads with removal in app purchase is something I want to add but it may be the most viable, because what else can I monetize? Making forums read-only with iAP to unlock sounds pretty sketchy (just random idea).

I did once put video ads on demand as a form of donation/support, but the traffic was so small that after a month I got exactly $0 so this is not the way to go.

What do you think? What seems appropriate for you to put behind a paywall?

(I'm bad in making profit from my apps, and I don't want to bomb you with ads in some random update and that's the TL;DR of this post xd)

**Comment by ZeroOmar** [comment]
maybe you can put ads in places that won't the app experience like an ad bar in the settings page

another option:
make 2 version of your app a free version and a paid version with more features

- a free version can access the anime an manga lists normally and visit profiles (something like you app back in version 3.x.x)

- a paid version has comments , forums , messaging, modifying favorites and all the greasy stuff XD

**Comment by Kimod** [comment]
I don't think that you should put features behind a pay wall, if you would want to go through that route, I think that you should make the whole app behind pay wall (Because someone could for example say, in the current build, there is this Issue and you could be like: "I already have that issue fixed 5 versions from this one, so I guess you have to wait...")

I think that you could do something like.. (I don't remember the app) ... When you went to the store, it had paid version and free trial, the free trial was unlimited, so who wanted could buy the paid version and who didn't want to pay, they could just stay on trial, which had the same features like the paid version (but this could scare away some people, when they see a price tag, some of them wouldn't know that trial is the same like the paid version)

But still maybe the adds in app may be the best solution to get some money out of people, who didn't already donate and would happily buy the addless version <-- me... ^^

**Comment by Mordonus** [comment]
Putting paywalls is not good in my opinion too and setting price on whole app is something I'd like to avoid.

I was thinking about putting ads in the bottom of most pages but not page with grid/list i.e details, calendar, articles so it'll encourage user to give me let's say $2 and get rid of them but the core stays unaffected.

Ppl who already donated anything or were/are/will be active on github would get keys to remove these ads.

**Comment by Mordonus** [comment]
Okay... ads... are something truly dreadful, so dreadful that I will hold them for later(if not forever). Implementing them takes so much time, effort and my sanity that I'd be able to finish up forums and that's what I'm going to do. Screw ads. :tada: 

There were 3 $3 donations in the past few days so something is (?) improving. Maybe I'll implement some fancy slider/text box with how much was donated in last week or so and increase frequency of donate pop-up.
